"""HTML element ID generators for virtual collection components."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto #0
__all__ = ['VirtualCollectionHtmlIds']

# %% ../../nbs/core/html_ids.ipynb #9b8b9ac9
from dataclasses import dataclass

# %% ../../nbs/core/html_ids.ipynb #3d0f88b9
@dataclass
class VirtualCollectionHtmlIds:
    """HTML element ID generators for a virtual collection instance."""
    prefix: str  # Instance prefix (e.g., 'vc0', 'fb')

    # -- Outer container --
    @property
    def collection(self) -> str: return f"{self.prefix}-collection"

    # -- Header --
    @property
    def header(self) -> str: return f"{self.prefix}-header"

    # -- Viewport --
    @property
    def viewport(self) -> str: return f"{self.prefix}-viewport"

    # -- Rows container (OOB swap target for navigation) --
    @property
    def rows(self) -> str: return f"{self.prefix}-rows"

    # -- Dynamic row/cell/item IDs --
    def row_id(self, index: int) -> str:  # ID for a table row
        return f"{self.prefix}-row-{index}"

    def cell_id(self, row_index: int, col_key: str) -> str:  # ID for a table cell
        return f"{self.prefix}-row-{row_index}-col-{col_key}"

    def item_id(self, index: int) -> str:  # ID for a grid item
        return f"{self.prefix}-item-{index}"

    # -- Custom scrollbar --
    @property
    def scrollbar_track(self) -> str: return f"{self.prefix}-scrollbar-track"

    @property
    def scrollbar_thumb(self) -> str: return f"{self.prefix}-scrollbar-thumb"

    # -- Footer --
    @property
    def footer(self) -> str: return f"{self.prefix}-footer"

    # -- Progress indicator --
    @property
    def progress(self) -> str: return f"{self.prefix}-progress"

    # -- Hidden inputs --
    @property
    def window_start_input(self) -> str: return f"{self.prefix}-window-start-input"
