"""Pure math functions for viewport window and scrollbar calculations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/windowing.ipynb.

# %% auto #0
__all__ = ['clamp_window_start', 'compute_window', 'compute_scrollbar', 'navigate', 'compute_visible_rows']

# %% ../../nbs/core/windowing.ipynb #de24143e
from typing import Tuple

# %% ../../nbs/core/windowing.ipynb #7c6e5c1f
def clamp_window_start(window_start: int,  # Requested first visible row
                       visible_rows: int,   # Number of visible rows
                       total_items: int,     # Total item count
                      ) -> int:              # Clamped window_start
    """Clamp window_start to valid range."""
    if total_items <= 0: return 0
    max_start = max(0, total_items - visible_rows)
    return max(0, min(window_start, max_start))

# %% ../../nbs/core/windowing.ipynb #191747f6
def compute_window(window_start: int,   # First visible row index (already clamped)
                   visible_rows: int,    # Number of visible rows
                   total_items: int,     # Total item count
                  ) -> Tuple[int, int]:  # (render_start, render_end) exclusive end
    """Compute the range of rows to render."""
    if total_items <= 0: return (0, 0)
    render_start = max(0, window_start)
    render_end = min(total_items, window_start + visible_rows)
    return (render_start, render_end)

# %% ../../nbs/core/windowing.ipynb #61b4cb18
def compute_scrollbar(window_start: int,      # First visible row index
                      visible_rows: int,       # Number of visible rows
                      total_items: int,        # Total item count
                      track_height: float,     # Scrollbar track height in px
                      min_thumb_height: int = 24,  # Minimum thumb height in px
                     ) -> Tuple[float, float]: # (thumb_top_percent, thumb_height_percent)
    """Compute scrollbar thumb position and size as percentages."""
    if total_items <= 0 or visible_rows >= total_items:
        return (0.0, 100.0)  # Thumb fills entire track

    # Thumb height as proportion of visible/total
    thumb_height_pct = (visible_rows / total_items) * 100.0

    # Enforce minimum thumb height
    if track_height > 0:
        min_pct = (min_thumb_height / track_height) * 100.0
        thumb_height_pct = max(thumb_height_pct, min_pct)

    # Thumb position
    max_start = max(1, total_items - visible_rows)
    thumb_top_pct = (window_start / max_start) * (100.0 - thumb_height_pct)

    return (thumb_top_pct, thumb_height_pct)

# %% ../../nbs/core/windowing.ipynb #4a93fc21
def navigate(window_start: int,   # Current first visible row
             direction: str,       # 'up', 'down', 'page_up', 'page_down', 'first', 'last'
             visible_rows: int,    # Number of visible rows
             total_items: int,     # Total item count
            ) -> int:              # New window_start (clamped)
    """Compute new window_start for a navigation action."""
    if direction == 'up':
        new_start = window_start - 1
    elif direction == 'down':
        new_start = window_start + 1
    elif direction == 'page_up':
        page_size = max(1, visible_rows - 1)
        new_start = window_start - page_size
    elif direction == 'page_down':
        page_size = max(1, visible_rows - 1)
        new_start = window_start + page_size
    elif direction == 'first':
        new_start = 0
    elif direction == 'last':
        new_start = max(0, total_items - visible_rows)
    else:
        raise ValueError(f"Unknown direction: {direction}")

    return clamp_window_start(new_start, visible_rows, total_items)

# %% ../../nbs/core/windowing.ipynb #2d05f4a5
def compute_visible_rows(viewport_height: float,  # Available height in px
                         row_height: int,          # Row height in px
                        ) -> int:                  # Number of visible rows
    """Compute how many rows fit in the viewport."""
    if row_height <= 0 or viewport_height <= 0: return 0
    return max(1, int(viewport_height // row_height))
