"""JavaScript generator for automatic visible row count adjustment based on viewport height."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/auto_fit.ipynb.

# %% auto #0
__all__ = ['generate_auto_fit_js', 'auto_fit_callback_name']

# %% ../../nbs/js/auto_fit.ipynb #8f683fda
from ..core.html_ids import VirtualCollectionHtmlIds
from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionUrls,
)

# %% ../../nbs/js/auto_fit.ipynb #d5ac25fe
def generate_auto_fit_js(
    ids: VirtualCollectionHtmlIds,       # HTML IDs for this collection
    config: VirtualCollectionConfig,      # Collection config (for row_height)
    urls: VirtualCollectionUrls,          # URL bundle (for update_viewport)
    debug: bool = False,                  # Enable console.log debugging
) -> str:  # JavaScript code fragment
    """Generate JS for auto-fitting visible row count to viewport height.
    
    Uses ResizeObserver on the viewport element to detect height changes from
    viewport-fit. Pure arithmetic: visibleRows = floor(viewportHeight / rowHeight).
    """
    if debug:
        dbg = """
                console.log('[auto-fit] called, viewport:', viewport?.id, 'offsetHeight:', viewportHeight, 'rowHeight:', rowHeight, 'visibleRows:', visibleRows, 'last:', _lastVisibleRows);
        """
        dbg_skip = """
                console.log('[auto-fit] skipped — same count:', visibleRows);
        """
        dbg_send = """
                console.log('[auto-fit] sending update_viewport:', visibleRows);
        """
    else:
        dbg = dbg_skip = dbg_send = ""

    return f"""
        // === Auto-Fit Visible Rows ===
        (function() {{
            let _lastVisibleRows = 0;

            window._vcAutoFit_{config.prefix} = function() {{
                const viewport = document.getElementById('{ids.viewport}');
                if (!viewport) return;

                const viewportHeight = viewport.offsetHeight;
                if (viewportHeight <= 0) return;

                const rowHeight = {config.row_height};
                const visibleRows = Math.max(1, Math.floor(viewportHeight / rowHeight));
                {dbg}
                // Only send update if count actually changed
                if (visibleRows === _lastVisibleRows) {{{dbg_skip}
                    return;
                }}
                _lastVisibleRows = visibleRows;
                {dbg_send}
                htmx.ajax('POST', '{urls.update_viewport}', {{
                    swap: 'none',
                    values: {{ visible_rows: visibleRows, is_auto: 'true' }}
                }});
            }};

            // Watch viewport for height changes (set by viewport-fit)
            const viewport = document.getElementById('{ids.viewport}');
            if (viewport) {{
                const observer = new ResizeObserver(function() {{
                    window._vcAutoFit_{config.prefix}();
                }});
                observer.observe(viewport);
            }}
        }})();
    """

# %% ../../nbs/js/auto_fit.ipynb #d4950ae4
def auto_fit_callback_name(
    config: VirtualCollectionConfig,  # Collection config (for prefix)
) -> str:  # Global JS function name
    """Get the global callback name for viewport-fit's resize_callback."""
    return f"window._vcAutoFit_{config.prefix}()"
