"""Main entry point for rendering a virtual collection."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/collection.ipynb.

# %% auto #0
__all__ = ['render_virtual_collection']

# %% ../../nbs/components/collection.ipynb #e0f08a9c
from typing import Any, Callable, List, Optional

from fasthtml.common import Div, Hidden

from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, flex_direction, flex
from cjm_fasthtml_tailwind.utilities.interactivity import touch
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState, VirtualCollectionUrls,
)
from ..core.html_ids import VirtualCollectionHtmlIds
from .table import render_header_row, render_table_rows
from .footer import render_footer
from .scrollbar import render_scrollbar

# %% ../../nbs/components/collection.ipynb #e0eadf8a
def render_virtual_collection(
    items: list,                                # Full item list
    config: VirtualCollectionConfig,             # Collection config
    state: VirtualCollectionState,               # Collection state
    ids: VirtualCollectionHtmlIds,               # HTML IDs
    urls: VirtualCollectionUrls,                 # URL bundle
    render_cell: Optional[Callable] = None,      # Table layout cell render callback
    render_item: Optional[Callable] = None,      # Grid layout item render callback
) -> Div:  # Complete collection element
    """Render a complete virtual collection with header, viewport, scrollbar, and footer."""
    children = []

    if config.layout == "table":
        assert render_cell is not None, "render_cell required for table layout"

        # Header (fixed, outside viewport)
        children.append(render_header_row(config, ids))

        # Viewport body (rows) + scrollbar side-by-side
        rows = render_table_rows(items, config, state, ids, render_cell, focus_url=urls.focus_row)
        viewport = Div(
            rows,
            id=ids.viewport,
            cls=combine_classes(flex(1), overflow.hidden),
        )

        if config.show_scrollbar and state.total_items > state.visible_rows:
            scrollbar = render_scrollbar(state, config, ids)
            body = Div(viewport, scrollbar, cls=combine_classes(flex_display))
        else:
            body = viewport

        children.append(body)

    elif config.layout == "grid":
        raise NotImplementedError("Grid layout will be added in Phase 14")
    else:
        raise ValueError(f"Unknown layout: {config.layout}")

    # Footer
    children.append(render_footer(state, ids))

    # Hidden input for JS thumb positioning (OOB-updated on navigation)
    children.append(Hidden(
        value=str(state.window_start),
        id=ids.window_start_input,
        name="window_start",
    ))

    return Div(
        *children,
        id=ids.collection,
        cls=combine_classes(flex_display, flex_direction.col, touch.none),
    )
