"""Custom scrollbar component with proportional thumb for position indication."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/scrollbar.ipynb.

# %% auto #0
__all__ = ['render_scrollbar_thumb', 'render_scrollbar']

# %% ../../nbs/components/scrollbar.ipynb #cc5726fe
from fasthtml.common import Div

from cjm_fasthtml_tailwind.utilities.sizing import w, h
from cjm_fasthtml_tailwind.utilities.layout import position
from cjm_fasthtml_tailwind.utilities.interactivity import cursor, select
from cjm_fasthtml_tailwind.utilities.transitions_and_animation import transition, duration
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui
from cjm_fasthtml_daisyui.utilities.border_radius import border_radius

from ..core.models import VirtualCollectionConfig, VirtualCollectionState
from ..core.html_ids import VirtualCollectionHtmlIds
from ..core.windowing import compute_scrollbar

# %% ../../nbs/components/scrollbar.ipynb #68eb98ff
def render_scrollbar_thumb(
    state: VirtualCollectionState,       # Collection state
    config: VirtualCollectionConfig,      # Collection config
    ids: VirtualCollectionHtmlIds,        # HTML IDs
    track_height: float = 600.0,          # Track height for min thumb calculation
    oob: bool = False,                    # Whether to include hx-swap-oob
) -> Div:  # Thumb element
    """Render the scrollbar thumb at the correct position."""
    thumb_top, thumb_height = compute_scrollbar(
        state.window_start, state.visible_rows, state.total_items,
        track_height, config.min_thumb_height,
    )

    thumb = Div(
        id=ids.scrollbar_thumb,
        cls=combine_classes(
            position.absolute, w.full, border_radius.field,
            bg_dui.base_content.opacity(30),
            cursor.grab,
        ),
        style=f"top: {thumb_top:.2f}%; height: {thumb_height:.2f}%",
    )

    if oob:
        thumb.attrs["hx-swap-oob"] = "outerHTML"

    return thumb

# %% ../../nbs/components/scrollbar.ipynb #502f2a2e
def render_scrollbar(
    state: VirtualCollectionState,       # Collection state
    config: VirtualCollectionConfig,      # Collection config
    ids: VirtualCollectionHtmlIds,        # HTML IDs
) -> Div:  # Complete scrollbar (track + thumb)
    """Render the custom scrollbar with track and proportional thumb."""
    # Don't show if all items visible
    if state.total_items <= state.visible_rows:
        return Div(id=ids.scrollbar_track)

    thumb = render_scrollbar_thumb(state, config, ids)

    return Div(
        thumb,
        id=ids.scrollbar_track,
        cls=combine_classes(
            w(2), position.relative, border_radius.field,
            bg_dui.base_content.opacity(10),
            cursor.pointer, select.none,
        ),
        data_total_items=str(state.total_items),
        data_visible_rows=str(state.visible_rows),
    )
