"""Table layout rendering: header row, data rows, and cells using CSS table display."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/table.ipynb.

# %% auto #0
__all__ = ['render_header_cell', 'render_header_row', 'render_data_cell', 'render_data_row', 'render_slot', 'render_table_rows',
           'render_cell_oob', 'render_row_oob']

# %% ../../nbs/components/table.ipynb #78dad85f
from typing import Any, Callable, List, Optional, Tuple

from fasthtml.common import Div, Span

from cjm_fasthtml_tailwind.utilities.spacing import p
from cjm_fasthtml_tailwind.utilities.typography import font_weight, truncate, font_size
from cjm_fasthtml_tailwind.utilities.borders import border
from cjm_fasthtml_tailwind.utilities.interactivity import cursor as cursor_tw
from cjm_fasthtml_tailwind.utilities.layout import display_tw
from cjm_fasthtml_tailwind.utilities.tables import table_display
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_daisyui.utilities.semantic_colors import border_dui, bg_dui

from cjm_fasthtml_virtual_collection.core.models import (
    ColumnDef, VirtualCollectionConfig, VirtualCollectionState,
    CellRenderContext, RowRenderContext,
)
from ..core.html_ids import VirtualCollectionHtmlIds

# %% ../../nbs/components/table.ipynb #c45cb2ee
def render_header_cell(column: ColumnDef,  # Column definition
                      ) -> Div:  # Header cell element
    """Render a single table header cell."""
    cls = combine_classes(
        table_display.cell,
        p.x(2), p.y(1),
        font_weight.semibold, font_size.sm,
        truncate,
        border.b(), border_dui.base_300,
        column.header_cls or None,
    )
    return Div(Span(column.header) if column.header else "", cls=cls)

# %% ../../nbs/components/table.ipynb #0eabb26b
def render_header_row(config: VirtualCollectionConfig,  # Collection config
                      ids: VirtualCollectionHtmlIds,     # HTML IDs
                     ) -> Div:  # Header row element
    """Render the table header row."""
    cells = [render_header_cell(col) for col in config.columns]
    return Div(
        *cells,
        id=ids.header,
        cls=combine_classes(table_display.row, bg_dui.base_200),
    )

# %% ../../nbs/components/table.ipynb #b6c98199
def render_data_cell(item: Any,                    # Data item
                     column: ColumnDef,             # Column definition
                     row_index: int,                # Row index
                     total_items: int,              # Total item count
                     ids: VirtualCollectionHtmlIds,  # HTML IDs
                     render_cell: Callable,          # Consumer cell render callback
                     is_cursor: bool = False,        # Whether row is keyboard cursor
                    ) -> Div:  # Cell element with stable ID
    """Render a single data cell with a stable ID for OOB updates."""
    ctx = CellRenderContext(
        row_index=row_index,
        column=column,
        total_items=total_items,
        is_cursor=is_cursor,
    )
    content = render_cell(item, ctx)
    cls = combine_classes(
        table_display.cell,
        p.x(2), p.y(1),
        border.b(), border_dui.base_200,
        column.cell_cls or None,
    )
    return Div(
        content,
        id=ids.cell_id(row_index, column.key),
        cls=cls,
    )

# %% ../../nbs/components/table.ipynb #9284c20c
def render_data_row(item: Any,                       # Data item
                    row_index: int,                   # Row index in full collection
                    config: VirtualCollectionConfig,   # Collection config
                    state: VirtualCollectionState,     # Collection state
                    ids: VirtualCollectionHtmlIds,     # HTML IDs
                    render_cell: Callable,             # Consumer cell render callback
                    focus_url: str = "",               # URL for click-to-focus (empty = disabled)
                   ) -> Div:  # Row element with stable ID
    """Render a single data row with all cells."""
    is_cursor = (row_index == state.cursor_index)

    cells = [
        render_data_cell(
            item, col, row_index, state.total_items, ids, render_cell, is_cursor
        )
        for col in config.columns
    ]

    row_cls = combine_classes(
        table_display.row,
        bg_dui.base_200.hover,
        cursor_tw.pointer if focus_url else None,
        bg_dui.base_300 if is_cursor else None,
    )

    # Click-to-focus HTMX attributes (skip clicks on interactive children)
    focus_attrs = {}
    if focus_url:
        focus_attrs = dict(
            hx_post=f"{focus_url}?row_index={row_index}",
            hx_swap="none",
            hx_trigger="click[!event.target.closest('input,button,a')]",
        )

    return Div(
        *cells,
        id=ids.row_id(row_index),
        cls=row_cls,
        **focus_attrs,
    )

# %% ../../nbs/components/table.ipynb #v5btl2d4va
def render_slot(
    slot_index: int,                       # Position in viewport (0-based)
    item: Any,                             # Data item
    item_index: int,                       # Row index in full collection
    config: VirtualCollectionConfig,       # Collection config
    state: VirtualCollectionState,         # Collection state
    ids: VirtualCollectionHtmlIds,         # HTML IDs
    render_cell: Callable,                 # Consumer cell render callback
    oob: bool = False,                     # Whether to render as OOB swap
    focus_url: str = "",                   # URL for click-to-focus (empty = disabled)
) -> Div:  # Slot wrapper (display:contents) containing the data row
    """Render a viewport slot wrapping a data row with display:contents."""
    inner_row = render_data_row(
        item, item_index, config, state, ids, render_cell, focus_url=focus_url,
    )
    return Div(
        inner_row,
        id=ids.slot_id(slot_index),
        cls=combine_classes(display_tw.contents),
        hx_swap_oob="innerHTML" if oob else None,
    )

# %% ../../nbs/components/table.ipynb #510630aa
def render_table_rows(items: list,                       # Full item list
                      config: VirtualCollectionConfig,    # Collection config
                      state: VirtualCollectionState,      # Collection state
                      ids: VirtualCollectionHtmlIds,      # HTML IDs
                      render_cell: Callable,              # Consumer cell render callback
                      focus_url: str = "",                # URL for click-to-focus (empty = disabled)
                     ) -> Div:  # Table-row-group container with slot wrappers
    """Render all visible rows in the current window as a table-row-group."""
    from cjm_fasthtml_virtual_collection.core.windowing import compute_window

    render_start, render_end = compute_window(
        state.window_start, state.visible_rows, state.total_items
    )

    slots = [
        render_slot(
            slot_index=slot_idx, item=items[item_idx], item_index=item_idx,
            config=config, state=state, ids=ids, render_cell=render_cell,
            focus_url=focus_url,
        )
        for slot_idx, item_idx in enumerate(range(render_start, render_end))
    ]

    return Div(*slots, id=ids.rows, cls=combine_classes(table_display.row_group))

# %% ../../nbs/components/table.ipynb #gsvxddb56a8
def render_cell_oob(item: Any,                       # Data item
                    column: ColumnDef,                # Column to render
                    row_index: int,                   # Row index
                    total_items: int,                 # Total item count
                    ids: VirtualCollectionHtmlIds,    # HTML IDs
                    render_cell: Callable,            # Consumer cell render callback
                    is_cursor: bool = False,          # Whether row is keyboard cursor
                   ) -> Div:  # Cell element with hx-swap-oob
    """Render a single cell with OOB swap for targeted update."""
    cell = render_data_cell(item, column, row_index, total_items, ids, render_cell, is_cursor)
    cell.attrs["hx-swap-oob"] = "outerHTML"
    return cell


def render_row_oob(item: Any,                       # Data item
                   row_index: int,                   # Row index
                   config: VirtualCollectionConfig,  # Collection config
                   state: VirtualCollectionState,    # Collection state
                   ids: VirtualCollectionHtmlIds,    # HTML IDs
                   render_cell: Callable,            # Consumer cell render callback
                  ) -> Div:  # Row element with hx-swap-oob
    """Render a full row with OOB swap for targeted update."""
    row = render_data_row(item, row_index, config, state, ids, render_cell)
    row.attrs["hx-swap-oob"] = "outerHTML"
    return row
