"""Response builder functions for virtual collection navigation (Tier 1 API)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/handlers.ipynb.

# %% auto #0
__all__ = ['build_nav_response', 'build_cursor_move_response', 'handle_navigate', 'handle_navigate_to_index',
           'handle_update_viewport']

# %% ../../nbs/routes/handlers.ipynb #6fde5c29
from typing import Any, Callable, List, Tuple

from fasthtml.common import Hidden

from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState, VirtualCollectionUrls,
)
from ..core.html_ids import VirtualCollectionHtmlIds
from cjm_fasthtml_virtual_collection.core.windowing import (
    navigate, navigate_cursor, clamp_window_start, compute_window,
)
from ..components.table import render_slot, render_table_rows
from ..components.footer import render_footer

# %% ../../nbs/routes/handlers.ipynb #2adaa2a1
def _render_window_start_oob(
    state: VirtualCollectionState,     # Current state
    ids: VirtualCollectionHtmlIds,     # HTML IDs
) -> Hidden:  # Hidden input with OOB swap
    """Render OOB hidden input carrying the current window_start for JS thumb positioning."""
    return Hidden(
        value=str(state.window_start),
        id=ids.window_start_input,
        name="window_start",
        hx_swap_oob="outerHTML",
    )


def build_nav_response(
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (already mutated)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements (slot OOBs + footer + window_start input)
    """Build OOB response for navigation: all visible slots + footer + window_start."""
    render_start, render_end = compute_window(
        state.window_start, state.visible_rows, state.total_items
    )

    slot_oobs = [
        render_slot(
            slot_index=slot_idx, item=items[item_idx], item_index=item_idx,
            config=config, state=state, ids=ids, render_cell=render_cell, oob=True,
        )
        for slot_idx, item_idx in enumerate(range(render_start, render_end))
    ]

    return tuple(slot_oobs) + (
        render_footer(state, ids, oob=True),
        _render_window_start_oob(state, ids),
    )

# %% ../../nbs/routes/handlers.ipynb #d3rfjri5i06
def build_cursor_move_response(
    old_cursor: int,                        # Previous cursor index
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (cursor already updated)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements (affected slot OOBs + footer + window_start input)
    """Build OOB response for cursor-only move: swap just the affected slots."""
    oob_parts = []

    # Re-render old cursor slot (remove highlight)
    if old_cursor != state.cursor_index:
        old_slot = old_cursor - state.window_start
        oob_parts.append(render_slot(
            slot_index=old_slot, item=items[old_cursor], item_index=old_cursor,
            config=config, state=state, ids=ids, render_cell=render_cell, oob=True,
        ))

    # Re-render new cursor slot (add highlight)
    new_slot = state.cursor_index - state.window_start
    oob_parts.append(render_slot(
        slot_index=new_slot, item=items[state.cursor_index], item_index=state.cursor_index,
        config=config, state=state, ids=ids, render_cell=render_cell, oob=True,
    ))

    oob_parts.append(render_footer(state, ids, oob=True))
    oob_parts.append(_render_window_start_oob(state, ids))

    return tuple(oob_parts)

# %% ../../nbs/routes/handlers.ipynb #321e1995
def handle_navigate(
    direction: str,                         # 'up', 'down', 'page_up', 'page_down', 'first', 'last'
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (mutated in place)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements
    """Navigate in a direction. Mutates state in place."""
    if direction in ('up', 'down'):
        old_cursor = state.cursor_index
        new_cursor, new_window_start, window_changed = navigate_cursor(
            state.cursor_index, direction, state.window_start,
            state.visible_rows, state.total_items,
        )
        state.cursor_index = new_cursor
        state.window_start = new_window_start

        if window_changed:
            return build_nav_response(items, state, config, ids, render_cell)
        else:
            return build_cursor_move_response(old_cursor, items, state, config, ids, render_cell)
    else:
        state.window_start = navigate(
            state.window_start, direction, state.visible_rows, state.total_items
        )
        return build_nav_response(items, state, config, ids, render_cell)

# %% ../../nbs/routes/handlers.ipynb #bb86598d
def handle_navigate_to_index(
    target_index: int,                      # Target window_start
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (mutated in place)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements (rows + footer)
    """Navigate to a specific index. Mutates state.window_start in place."""
    state.window_start = clamp_window_start(
        target_index, state.visible_rows, state.total_items
    )
    return build_nav_response(items, state, config, ids, render_cell)

# %% ../../nbs/routes/handlers.ipynb #72c4a7a1
def _build_container_response(
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements (container + footer + window_start input)
    """Build OOB response that replaces the entire rows container with new slots."""
    rows_oob = render_table_rows(items, config, state, ids, render_cell)
    rows_oob.attrs["hx-swap-oob"] = "outerHTML"
    return (
        rows_oob,
        render_footer(state, ids, oob=True),
        _render_window_start_oob(state, ids),
    )


def handle_update_viewport(
    visible_rows: int,                      # New visible row count
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (mutated in place)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
    is_auto: bool = True,                   # Whether from auto-fit
) -> Tuple:  # OOB elements
    """Update viewport with new row count. Mutates state in place."""
    visible_rows = max(1, visible_rows)
    state.visible_rows = visible_rows
    state.is_auto_mode = is_auto
    state.window_start = clamp_window_start(
        state.window_start, state.visible_rows, state.total_items
    )
    # Replace entire container — slot count changed
    return _build_container_response(items, state, config, ids, render_cell)
