"""Response builder functions for virtual collection navigation (Tier 1 API)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/handlers.ipynb.

# %% auto #0
__all__ = ['build_nav_response', 'handle_navigate', 'handle_navigate_to_index', 'handle_update_viewport']

# %% ../../nbs/routes/handlers.ipynb #6fde5c29
from typing import Any, Callable, List, Tuple

from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState, VirtualCollectionUrls,
)
from ..core.html_ids import VirtualCollectionHtmlIds
from ..core.windowing import navigate, clamp_window_start
from ..components.table import render_table_rows
from ..components.footer import render_footer

# %% ../../nbs/routes/handlers.ipynb #2adaa2a1
def build_nav_response(
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (already mutated)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements (rows + footer)
    """Build OOB response for navigation: rows + footer."""
    rows_oob = render_table_rows(items, config, state, ids, render_cell)
    rows_oob.attrs["hx-swap-oob"] = "innerHTML"

    footer_oob = render_footer(state, ids, oob=True)

    return (rows_oob, footer_oob)

# %% ../../nbs/routes/handlers.ipynb #321e1995
def handle_navigate(
    direction: str,                         # 'up', 'down', 'page_up', 'page_down', 'first', 'last'
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (mutated in place)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements (rows + footer)
    """Navigate in a direction. Mutates state.window_start in place."""
    state.window_start = navigate(
        state.window_start, direction, state.visible_rows, state.total_items
    )
    return build_nav_response(items, state, config, ids, render_cell)

# %% ../../nbs/routes/handlers.ipynb #bb86598d
def handle_navigate_to_index(
    target_index: int,                      # Target window_start
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (mutated in place)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
) -> Tuple:  # OOB elements (rows + footer)
    """Navigate to a specific index. Mutates state.window_start in place."""
    state.window_start = clamp_window_start(
        target_index, state.visible_rows, state.total_items
    )
    return build_nav_response(items, state, config, ids, render_cell)

# %% ../../nbs/routes/handlers.ipynb #72c4a7a1
def handle_update_viewport(
    visible_rows: int,                      # New visible row count
    items: list,                            # Full item list
    state: VirtualCollectionState,          # Current state (mutated in place)
    config: VirtualCollectionConfig,        # Collection config
    ids: VirtualCollectionHtmlIds,          # HTML IDs
    render_cell: Callable,                  # Consumer cell render callback
    is_auto: bool = True,                   # Whether from auto-fit
) -> Tuple:  # OOB elements (rows + footer)
    """Update viewport with new row count. Mutates state in place."""
    state.visible_rows = max(1, visible_rows)
    state.is_auto_mode = is_auto
    # Re-clamp window_start in case new visible_rows changes the valid range
    state.window_start = clamp_window_start(
        state.window_start, state.visible_rows, state.total_items
    )
    return build_nav_response(items, state, config, ids, render_cell)
