"""Convenience router factory that wires up standard virtual collection routes (Tier 2 API)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/router.ipynb.

# %% auto #0
__all__ = ['init_virtual_collection_router']

# %% ../../nbs/routes/router.ipynb #711bb97a
from typing import Any, Callable, List, Tuple

from fasthtml.common import APIRouter

from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState, VirtualCollectionUrls,
)
from ..core.html_ids import VirtualCollectionHtmlIds
from cjm_fasthtml_virtual_collection.routes.handlers import (
    handle_navigate, handle_navigate_to_index, handle_update_viewport,
)

# %% ../../nbs/routes/router.ipynb #a93f7b39
def init_virtual_collection_router(
    config: VirtualCollectionConfig,                    # Collection config
    state_getter: Callable[[], VirtualCollectionState],  # Function to get current state
    state_setter: Callable[[VirtualCollectionState], None],  # Function to save state
    get_items: Callable[[], list],                       # Function to get current items
    render_cell: Callable,                               # Cell render callback
    route_prefix: str = "/collection",                   # Route prefix
) -> Tuple[APIRouter, VirtualCollectionUrls]:  # (router, urls) tuple
    """Initialize an APIRouter with all standard virtual collection routes."""
    router = APIRouter(prefix=route_prefix)
    ids = VirtualCollectionHtmlIds(prefix=config.prefix)

    # -----------------------------------------------------------------
    # Navigation routes
    # -----------------------------------------------------------------

    def _nav(direction: str) -> Any:
        """Shared navigation handler."""
        state = state_getter()
        items = get_items()
        result = handle_navigate(
            direction=direction, items=items, state=state,
            config=config, ids=ids, render_cell=render_cell,
        )
        state_setter(state)
        return result

    @router
    def nav_up() -> Any: return _nav("up")

    @router
    def nav_down() -> Any: return _nav("down")

    @router
    def nav_first() -> Any: return _nav("first")

    @router
    def nav_last() -> Any: return _nav("last")

    @router
    def nav_page_up() -> Any: return _nav("page_up")

    @router
    def nav_page_down() -> Any: return _nav("page_down")

    @router
    def nav_to_index(target_index: int) -> Any:
        """Navigate to a specific window_start index."""
        state = state_getter()
        items = get_items()
        result = handle_navigate_to_index(
            target_index=target_index, items=items, state=state,
            config=config, ids=ids, render_cell=render_cell,
        )
        state_setter(state)
        return result

    # -----------------------------------------------------------------
    # Viewport route
    # -----------------------------------------------------------------

    @router
    def update_viewport(visible_rows: int, is_auto: str = "true") -> Any:
        """Update viewport with new row count."""
        state = state_getter()
        items = get_items()
        result = handle_update_viewport(
            visible_rows=visible_rows, items=items, state=state,
            config=config, ids=ids, render_cell=render_cell,
            is_auto=(is_auto == "true"),
        )
        state_setter(state)
        return result

    # -----------------------------------------------------------------
    # Build URL bundle from registered routes
    # -----------------------------------------------------------------

    urls = VirtualCollectionUrls(
        nav_up=nav_up.to(),
        nav_down=nav_down.to(),
        nav_page_up=nav_page_up.to(),
        nav_page_down=nav_page_down.to(),
        nav_first=nav_first.to(),
        nav_last=nav_last.to(),
        nav_to_index=nav_to_index.to(),
        update_viewport=update_viewport.to(),
    )

    return router, urls
